name: Deploy book with Python

on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and deploys it to GitHub Pages
# only runs if "Update Metadata" workflow is successful
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
     
    
    # check all kernels 
    - name: Log all available kernels
      run: |
        jupyter kernelspec list

    # only caches if set up in _config.yml with:
    # execute:
    #   execute_notebooks: cache
    - name: Cache executed notebooks
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Upload book artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
